runtime: python39 # Or python38 if you're using Python 3.8

entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto

# You can define your environment variables here if needed:
env_variables:
  GOOGLE_CLOUD_STR: 'https://storage.cloud.google.com/anime-rec/anime_filtered.csv'

